/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_minify_in (XDR *xdrs, minify_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->src, ~0))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->src_len))
		 return FALSE;
	return TRUE;
}
